
# 开发环境配置
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/otabook?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /static/**
# 日志配置
logging:
  level:
    cn.com.softvan.audit: debug
server:
  port: 8082


# 系统配置
audit:
  upload:
    root-path: F:/home/softvan/data_sys_file_cmwx/upload
    web-path: /file

wechat:
  mp:
    appId: wx8cdd1b8280894cb7
    secret: 0a9945dc1dc5ae8fb610bc2f371d4e71
    token: 01b0b434613d451193b8117be9be1b94
    aesKey:
    mchId: 1433891402
    mchKey: 01c6449902ae07bcde97088b83692977
    keyPath: /mydata/home/softvan/software/pw/cert/apiclient_cert.p12


#最大连接数
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 1000
  staleConnectionCheckEnabled: true

