# 生产环境配置
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yysh_audit?useUnicode=true&characterEncoding=utf-8
    username: root
    password: softvan
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
# 日志配置
logging:
  level:
    cn.com.softvan.audit: error

